### ISSUE TITLE
End Portal BUG

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#24]
The portal linkage can happen ACROSS THE SAVES...

When I and my friend were playing in our world, we built a portal in the overworld and another one in the end. However when we exited and entered into another creative mode world, we were shocked that if no closer portals in the overworld were found, the portal in the end would link with the coords exactly as the one we placed in the overworld in the former world, just like a ghost portal: it doesn't exist in the world, yet it keeps stealing the stuff thrown in (when the portal is (stated to be) linked with it), items, redstone signals... maybe more like fluids but we didn't try that far. After relaunching minecraft, the ghost portal was gone.

There is a possibility that other portals may act similar, if they share some sections of the code. Please check.

Sorry that we didn't take screenshots. Were focusing on how to explain the bug whole time.

**Comment by GregoriusT** [comment]
Oh great, how the heck did that happen... I guess i need to clear the Portal Lists or check if the Worlds the Portals are in are actually valid.

Wait, even if the Portal is linked it should not be able to accept Items since it needs something to output to.

Can Portals emit Items in Entity Form? I am not 100% sure if they can.

**Comment by GregoriusT** [comment]
Okay, just to make 100% sure, did you run into the !!!Vanilla!!! Bug that has you join a different Singleplayer World, while the previous Singleplayer World is still loaded AND TICKING in the Background, resulting in TWO Savegames or instances of the same Savegame being loaded at the same time?

**Comment by BoBoLittleStar** [comment]
No of course I didn't do that, nor my laptop's memory allows it. I create the world and open it to LAN, then I set port forwarding of the router to let my friend in.

There was only once that the portal did not actually accept items when we were testing. It happened because we tried its other faces. I'm guessing it drops items in because there was an item pipe in the previous world and it brought whatever was saved as its attribute to the new world (didn't verify or check the code though, just my thought, might be wrong).

**Comment by GregoriusT** [comment]
I am saying that just because it is possible to somehow leave the Singleplayer Server open in the background WITHOUT you noticing, and the only way to see that is to check the Task Manager after closing Minecraft. GregTech-6 alone only uses about 1 GB of RAM, and it wont use significant additional RAM for each loaded World, so having 2 Worlds open at the same time is definitely possible even if you are low on RAM, since it is just like having a third Player join when it comes to RAM usage.

I did check my own Code to see how the Portals could still work even after shutdown, and normally the Portals would have been marked as Dead when they got unloaded, meaning there might have been something keeping them up in the background (since it is the very same java instance, and not actually a second game instance).

If the Local Server does not run in the background for "no good reason" after closing it, then the next Version will have the Bug fixed.

But if the Local Server DOES still run in the background after closing it, I cant really fix it, since even after clearing the Lists, that the Portals go through for finding their Destination, on startup and shutdown of a World, the Background Server would still do Game Ticks and just dump its Portals back into the Global Static List, making the efforts of removing those Portals futile.

**Comment by BoBoLittleStar** [comment]
I entered the game only once, plus the bug occurred after I exited the world and entered another one without closing Minecraft - there's no need to do so. After I closed and relaunched the game, the bug was gone.

If you are certain that this is the only way this could happen, you might want to check Railcraft Anchor. It's a block that forces a 3x3-chunk area loaded when the game doesn't want to.
how did I not notice this : (

The things around when we met this issue are this:
1. We were happy playing in World-1
2. I made an Enderman grinder in the End, placed an End Portal so that the pearls come home, and used Railcraft Anchor to keep it loaded
3. The grinder didn't work well, so I closed World-1 and entered World-2 for testing and improvement
4. Back to World-1, the portal starts stealing items
5. We entered another world World-3 to try to explain it
6. Found a "ghost portal" that should exists in World-1 as its coords stated, no matter what we do in World-3, it doesn't disappear
7. Finally we tried relaunching the game and the bug was fixed, the portal in World-3 says "no target" when there's no target
8. Back to World-1, the bug was gone, then we put it aside and were happy playing the game again

I'm not sure if you can reproduce this bug following above processes but the probability is not 0. There is a chance that it happened because I opened the world to LAN and let my friend in, so you might also want to do that - it's faster as well, since one can stay in the overworld and the other can stay in the End.

**Comment by GregoriusT** [comment]
Yeah this is how it happens:
- Launch Minecraft once
- Enter Singleplayer World once
- Leave Singleplayer World once (as in go back to Main Menu)
- Enter another Singleplayer World once
- And now there is two Worlds open at the same time
Yes, vanilla Minecraft is THAT broken.

If you leave a World without closing down Minecraft, there is a chance the World is still open in the background for no damn reason.

As I said, if what I described just now is what happened, then I do not think the Bug could be fixed.

But if what I just described was not the problem, then it will be fixed in the next Version, as I reset the Portal Lists whenever a World is closed/opened.

**Comment by BoBoLittleStar** [comment]
That's cool... first time heard that. I just thought it was something Railcraft Anchor did.

**Comment by GregoriusT** [comment]
Technically the Anchor keeps the Chunks loaded indeed, but the Chunks around the Spawn Point of the World do the very same thing in pure Vanilla too.

If you wanna see if the Issue with the Portals themselves got fixed in the upcoming Version, just test this Snapshot of mine:

https://gregtech.mechaenetia.com/secretdownloads/

The Link should be stable for the next couple of hours. ;)

**Comment by GregoriusT** [comment]
@BoBoLittleStar Is it safe to mark this Bug as Fixed now?

**Comment by BoBoLittleStar** [comment]
Sorry idk... Haven't played Minecraft for weeks : (

**Comment by GregoriusT** [comment]
Eh, dont worry, test it whenever you play again. ^^

**Comment by BoBoLittleStar** [comment]
Just tried once and I think the bug is gone : D
Still don't know if that bug from vanilla affects it.
